export enum TradingState {
  INITIALIZE = 'INITIALIZE',
  ORDER = 'ORDER',
  ORDER_PREPARED = 'ORDER_PREPARED',
  ORDER_EMPTY_SIDE_WITH_GAP = 'ORDER_EMPTY_SIDE_WITH_GAP',
  CLOSE_ORDERS = 'CLOSE_ORDERS',
  CLOSE_FOR_STOP = 'CLOSE_FOR_STOP',
  ORDER_CHECK = 'ORDER_CHECK',
  STOP = 'STOP',
}